<<<<<<< HEAD:studis/Models/Model1.cs
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

>>>>>>> upstream/master:studis/Models/Studis.cs
